{
 "title": "Nolus-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "chain_id",
    "query": {
     "query": "label_values(cosmos_validators_status, chain_id)"
    }
   },
   {
    "name": "moniker",
    "label": "moniker",
    "query": {
     "query": "label_values(cosmos_validator_status, moniker)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_memory_MemTotal_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n     <tr>\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><center><img width=\"180px\" src=\"https://crew3-production.s3.eu-west-3.amazonaws.com/public/fb4041f1-7c8a-4ba5-ba4a-60912245abe6-final.jpg\" /></td>\n     <td style=\"border:0px;\"><h1 style=\"font-family: 'Prompt', sans-serif;font-size: 36px;letter-spacing: 0px;word-spacing: 0px;font-weight: normal;text-decoration: none;font-style: normal;font-variant: normal;text-transform: none;\">Nolus Protocol</h1> \n     Network: <h2 style=\"font-family: 'Prompt', sans-serif;font-size: 25px;font-weight: normal;text-decoration: underline;\">Nolus-rila</h2></td> \n     </tr>\n</table>"
   }
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "NLS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\"}",
     "legendFormat": "{{NLS}}"
    }
   ]
  },
  {
   "title": "Block SIze",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Block Size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Most missed blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators Missed Blocks",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0))"
    }
   ]
  },
  {
   "title": "Validators missing blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(tendermint_consensus_height{chain_id=\"$chain_id\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(tendermint_consensus_height{chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 19 },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"nolus-rila\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}